version: '3.7'
services:
    elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            # Limit use of memory https://github.com/zammad/zammad-docker-compose/issues/256#issuecomment-1105241970
            - ES_JAVA_OPTS=-Xmx4096m
        ports:
            - 9200:9200

    kibana:
        container_name: kb-container
        image: docker.elastic.co/kibana/kibana:8.14.0
        environment:
            - ELASTICSEARCH_HOSTS=http://es-container:9200
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
